# Composite action to upload junit test result files to Datadog Test Optimization
name: "Datadog JUnitXML Upload"
description: "Upload JUnitXML reports files to Datadog Test Optimization"
inputs:
  api_key:
    required: true
    description: Datadog API key to use to upload the junit files.
  site:
    required: false
    default: datadoghq.com
    description: The Datadog site to upload the files to.
  files:
    required: true
    description: JUnit files to upload.
    default: .
  auto-discovery:
    required: true
    description: Do a recursive search and automatic junit files discovery in the folders provided in `files` input (current folder if omitted).
    default: 'true'
  ignored-paths:
    required: false
    description: A comma-separated list of paths that are ignored when junit files auto-discovery is done. Glob patterns are supported
  concurrency:
    required: true
    description: Controls the maximum number of concurrent file uploads.
    default: "20"
  node-version:
    required: true
    description: The node version used to install datadog-ci
    default: "20"
  tags:
    required: false
    description: Datadog tags to associate with the uploaded test results.
  service:
    required: false
    description: Service name to use with the uploaded test results.
  env:
    required: false
    description: Datadog env to use for the tests.
  logs:
    required: false
    description: Set to "true" to enable forwarding content from XML reports as logs.
  datadog-ci-version:
    required: false
    description: The version of the @datadog/datadog-ci package to use. Leave empty to use the bundled version from package.json (recommended for caching).
  extra-args:
    default: ""
    description: Extra args to be passed to the datadog-ci cli.
    required: false
runs:
  using: "composite"
  steps:
    - name: Resolve action path
      id: action-path
      shell: bash
      run: echo "path=$(cd "${{ github.action_path }}" && pwd)" >> "$GITHUB_OUTPUT"

    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
        cache-dependency-path: ${{ steps.action-path.outputs.path }}/package-lock.json

    - name: Install datadog-ci (bundled version)
      if: inputs.datadog-ci-version == ''
      shell: bash
      working-directory: ${{ github.action_path }}
      run: npm ci

    - name: Upload the JUnit files
      shell: bash
      run: |
        if [ -n "${{ inputs.datadog-ci-version }}" ]; then
          DATADOG_CI="npx @datadog/datadog-ci@${{ inputs.datadog-ci-version }}"
        else
          DATADOG_CI="${{ github.action_path }}/node_modules/.bin/datadog-ci"
        fi

        $DATADOG_CI junit upload \
          --max-concurrency ${{ inputs.concurrency }} \
          ${{ inputs.logs == 'true' && '--logs' || '' }} \
          ${{ inputs.auto-discovery == 'true' && '--auto-discovery' || '' }} \
          ${{ inputs.ignored-paths != '' && format('--ignored-paths {0}', inputs.ignored-paths) || '' }} \
          ${{ inputs.service != '' && format('--service {0}', inputs.service) || '' }} \
          ${{ inputs.extra-args }} \
          ${{ inputs.files }}
      env:
        DD_API_KEY: ${{ inputs.api_key }}
        DD_SITE: ${{ inputs.site }}
        DD_ENV: ${{ inputs.env }}
        DD_TAGS: ${{ inputs.tags }}
